let is_not_space char = char <> ' ' && char <> '\t'
let quote str = "\"" ^ str ^ "\""

let unquote str =
  let firstchar = String.get str 0 in
  let lastindex = String.length str - 1 in
  let lastchar = String.get str lastindex in
  match firstchar, lastchar with
  | '"', '"' -> String.sub str 1 (lastindex - 1)
  | _, _ -> str
;;

let get_current_date () =
  let today = Unix.localtime (Unix.time ()) in
  let day = today.Unix.tm_mday in
  let month = today.Unix.tm_mon + 1 in
  let year = today.Unix.tm_year + 1900 in
  Printf.sprintf "The current date is %04d-%02d-%02d" year month day
;;

let get_absolute_file_path file = file |> unquote |> Filename_unix.realpath

let is_valid_path path =
  path
  |> get_absolute_file_path
  |> Sys.file_exists
;;

let set_working_directory input =
  let full_path = input |> get_absolute_file_path in
  full_path |> Filename.dirname |> Sys.chdir;
  full_path
;;

let read_file path =
  let channel = open_in path in
  let len = in_channel_length channel in
  let content = really_input_string channel len in
  close_in channel;
  content
;;

let write_file path content =
  let dated_content =
    Printf.sprintf
      {|// This file was autogenerated. DO NOT modify this file by hand.
// Generated on %s
%s
  |}
      (get_current_date ())
      content
  in
  let channel = open_out path in
  output_string channel (dated_content |> String.trim);
  output_string channel "\n";
  close_out channel
;;
