name: "[conkeldurr/ci] Lint source code and run unit tests on push and PR"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          cache-prefix: v1
          dune-cache: true

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          cache-prefix: v1
          dune-cache: true
      
      - name: Install dependencies
        run: opam install . --deps-only

      - name: Lint code
        run: eval $(opam env) && dune fmt

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          cache-prefix: v1
          dune-cache: true
      
      - name: Install dependencies
        run: opam install . --deps-only

      - name: Run tests
        run: eval $(opam env) && dune runtest
